site_name: ACWA

nav:
  - Home: index.md
  - General Structure: general_structure.md
  - Metadata Upload: metadata_upload.md
  - Power Curves: power_curves.md    
  - Data Mockup: data_mockup.md  
  - Data Collection: data_collection.md
  - Alarms Treatment: alarms_treatment.md
  - Reliability: reliability.md

  - Full Scheme: full_scheme_2.md

plugins:
  - search
  - mermaid2
  - include-markdown

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js